### ISSUE TITLE
Running into issue when extracting mesh

### ISSUE THREAD

**Issue by xavierpuigf** [video2game/video2game#8]
Thanks for the great work! I managed to reproduce the garden scene but I am having trouble using my own scenes. Wondering if you have insights on hyperparameters that could help resolve it?

I am able to train the nerf from my video, but when I run extract_mesh I get the following error. It doesn't look like it is a problem with the number of faces or vertices, cause I am able to run marching cubes where the number is larger. Have you run into this, and do you have any tips for solving this?

Thanks so much!

```
>> CUDA_LAUNCH_BLOCKING=1 sh scripts/extract_mesh/extract_mesh_garden.sh
[INFO] mesh mask trigs: (7374364, 3) --> (5338735, 3), (14650683, 3) --> (10578308, 3)
1, 0, 1; bounding box: x: 0.3233333333333333, 0.6666666666666666; y: 0.0, 0.3333333333333333 z: 0.49, 0.6
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 25.33it/s]
density:  tensor(294.2611) tensor(-18.8536)
start marching cubes
finish marching cubes
num_verts:  4532535
num_faces:  9087993
  0%|                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | 0/185 [00:00<?, ?it/s]
torch.Size([1, 9861895, 4]) torch.Size([19653377, 3])
  0%|                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | 0/185 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "extract_mesh.py", line 653, in <module>
    visibility_mask = mark_unseen_triangles(glctx, mesh_points, faces, dataset.mvps, dataset.H, dataset.W).cpu().numpy()
  File "/private/home/xavierpuig/.conda/envs/video2game/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "extract_mesh.py", line 143, in mark_unseen_triangles
    rast_p, _ = dr.rasterize(glctx, vertices_clip, triangles, (H, W)) # [1, H, W, 4]
  File "/private/home/xavierpuig/.conda/envs/video2game/lib/python3.7/site-packages/nvdiffrast/torch/ops.py", line 317, in rasterize
    return _rasterize_func.apply(glctx, pos, tri, resolution, ranges, grad_db, -1)
  File "/private/home/xavierpuig/.conda/envs/video2game/lib/python3.7/site-packages/nvdiffrast/torch/ops.py", line 255, in forward
    out, out_db = _get_plugin().rasterize_fwd_cuda(raster_ctx.cpp_wrapper, pos, tri, resolution, ranges, peeling_idx)
RuntimeError: Cuda error: 700[cudaLaunchKernel((void*)triangleSetupKernel, dim3(setupBlocks, 1, m_numImages), dim3(32, CR_SETUP_WARPS), args, 0, stream);]
```

**Comment by anonymous5433** [comment]
> Thanks for the great work! I managed to reproduce the garden scene but I am having trouble using my own scenes. Wondering if you have insights on hyperparameters that could help resolve it?
> 
> I am able to train the nerf from my video, but when I run extract_mesh I get the following error. It doesn't look like it is a problem with the number of faces or vertices, cause I am able to run marching cubes where the number is larger. Have you run into this, and do you have any tips for solving this?
> 
> Thanks so much!
> 
> ```
> >> CUDA_LAUNCH_BLOCKING=1 sh scripts/extract_mesh/extract_mesh_garden.sh
> [INFO] mesh mask trigs: (7374364, 3) --> (5338735, 3), (14650683, 3) --> (10578308, 3)
> 1, 0, 1; bounding box: x: 0.3233333333333333, 0.6666666666666666; y: 0.0, 0.3333333333333333 z: 0.49, 0.6
> 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 25.33it/s]
> density:  tensor(294.2611) tensor(-18.8536)
> start marching cubes
> finish marching cubes
> num_verts:  4532535
> num_faces:  9087993
>   0%|                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | 0/185 [00:00<?, ?it/s]
> torch.Size([1, 9861895, 4]) torch.Size([19653377, 3])
>   0%|                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | 0/185 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "extract_mesh.py", line 653, in <module>
>     visibility_mask = mark_unseen_triangles(glctx, mesh_points, faces, dataset.mvps, dataset.H, dataset.W).cpu().numpy()
>   File "/private/home/xavierpuig/.conda/envs/video2game/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
>     return func(*args, **kwargs)
>   File "extract_mesh.py", line 143, in mark_unseen_triangles
>     rast_p, _ = dr.rasterize(glctx, vertices_clip, triangles, (H, W)) # [1, H, W, 4]
>   File "/private/home/xavierpuig/.conda/envs/video2game/lib/python3.7/site-packages/nvdiffrast/torch/ops.py", line 317, in rasterize
>     return _rasterize_func.apply(glctx, pos, tri, resolution, ranges, grad_db, -1)
>   File "/private/home/xavierpuig/.conda/envs/video2game/lib/python3.7/site-packages/nvdiffrast/torch/ops.py", line 255, in forward
>     out, out_db = _get_plugin().rasterize_fwd_cuda(raster_ctx.cpp_wrapper, pos, tri, resolution, ranges, peeling_idx)
> RuntimeError: Cuda error: 700[cudaLaunchKernel((void*)triangleSetupKernel, dim3(setupBlocks, 1, m_numImages), dim3(32, CR_SETUP_WARPS), args, 0, stream);]
> ```

Hello,sorry to bother you.I've met problem the same as you. I'm wondering if you've fixed it. Wish you a good day!

**Comment by xavierpuigf** [comment]
I didn't, but I believe it is due to an OOM error. I solved it by getting better NERF reconstructions before extracting the mesh, which creates less unseen triangles. You can also try to set `mesh_post_process` to False. You will end up with a much bigger mesh, but it won't crash.

**Comment by xiahongchi** [comment]
It should be the problem of gpu out of memory. it's suggested to simplify the mesh before using dr.rasterize()

**Comment by PandaZ0912** [comment]
> 感谢你们的出色工作！我设法再现了花园场景，但我在使用自己的场景时遇到了问题。想知道您是否对超参数有见解可以帮助解决这个问题？
> 
> 我能够从我的视频中训练 nerf，但是当我运行 extract_mesh 时，我收到以下错误。看起来面数或顶点数没有问题，因为我能够在数量较大的地方运行行进立方体。你遇到过这个问题吗，你有什么解决这个问题的技巧吗？
> 
> 非常感谢！
> 
> ```
> >> CUDA_LAUNCH_BLOCKING=1 sh scripts/extract_mesh/extract_mesh_garden.sh
> [INFO] mesh mask trigs: (7374364, 3) --> (5338735, 3), (14650683, 3) --> (10578308, 3)
> 1, 0, 1; bounding box: x: 0.3233333333333333, 0.6666666666666666; y: 0.0, 0.3333333333333333 z: 0.49, 0.6
> 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 25.33it/s]
> density:  tensor(294.2611) tensor(-18.8536)
> start marching cubes
> finish marching cubes
> num_verts:  4532535
> num_faces:  9087993
>   0%|                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | 0/185 [00:00<?, ?it/s]
> torch.Size([1, 9861895, 4]) torch.Size([19653377, 3])
>   0%|                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | 0/185 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "extract_mesh.py", line 653, in <module>
>     visibility_mask = mark_unseen_triangles(glctx, mesh_points, faces, dataset.mvps, dataset.H, dataset.W).cpu().numpy()
>   File "/private/home/xavierpuig/.conda/envs/video2game/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
>     return func(*args, **kwargs)
>   File "extract_mesh.py", line 143, in mark_unseen_triangles
>     rast_p, _ = dr.rasterize(glctx, vertices_clip, triangles, (H, W)) # [1, H, W, 4]
>   File "/private/home/xavierpuig/.conda/envs/video2game/lib/python3.7/site-packages/nvdiffrast/torch/ops.py", line 317, in rasterize
>     return _rasterize_func.apply(glctx, pos, tri, resolution, ranges, grad_db, -1)
>   File "/private/home/xavierpuig/.conda/envs/video2game/lib/python3.7/site-packages/nvdiffrast/torch/ops.py", line 255, in forward
>     out, out_db = _get_plugin().rasterize_fwd_cuda(raster_ctx.cpp_wrapper, pos, tri, resolution, ranges, peeling_idx)
> RuntimeError: Cuda error: 700[cudaLaunchKernel((void*)triangleSetupKernel, dim3(setupBlocks, 1, m_numImages), dim3(32, CR_SETUP_WARPS), args, 0, stream);]
> ```

Hello, I would like to ask what segmentation tool you used when reconstructing the Gardenvase scene? Thank you!
